namespace MyBudgetApp.Models
{
    public enum ExpenseCategoryEnum
    {
        InternetAndTV,
        GasUtilityService,
        WaterUtilityService,
        WasteUtilityService,
        ElectricityUtilityService,
        LunchTinus,
        LunchLoci,
        MobileServiceFee,
        Cigarette,
        Shopping,
        Fuel,
        PublicTransportFee,
        Clothes,
        Recreation,
        Car,
        BankLoan,
        Savings,
        BankCharges,
        HealthCare,
        Gifts,
        Childs,
        Learning,
        Other,
        Travel
    }
}
